PgClientApplication/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PgClientApplication.Models
{
    public class Book
    {
        public int BookingId { get; set; }
        public int pg_Id { get; set; }

        public int UserId { get; set; }
        public DateTime BookingDate { get; set; }
        public int No_ofMonth { get; set; }
        public double TotalCost { get; set; }
    }
}

PgClientApplication/Controllers/PgListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PgClientApplication.Models;

namespace PgClientApplication.Controllers
{
    public class PgListController : Controller
    {
      
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(PgListController));
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("token") == null)
            {
                _log4net.Info("token not found");

                return RedirectToAction("Login");

            }
            else
            {
                _log4net.Info("Productlist getting Displayed");

                List<Pg> ItemList = new List<Pg>();
                using (var client = new HttpClient())
                {


                    var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                    client.DefaultRequestHeaders.Accept.Add(contentType);

                    client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

                    using (var response = await client.GetAsync("https://localhost:44345/api/Pg"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        ItemList = JsonConvert.DeserializeObject<List<Pg>>(apiResponse);
                    }
                }
                return View(ItemList);

            }
        }
        public async Task<IActionResult> Book(int id)
        {
            _log4net.Info("Booking in progess");
            if (HttpContext.Session.GetString("token") == null)
            {

                return RedirectToAction("Login", "Login");

            }
            else
            {

                Pg Item = new Pg();
                Book b = new Book();
                using (var client = new HttpClient())
                {


                    var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                    client.DefaultRequestHeaders.Accept.Add(contentType);

                    client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

                    using (var response = await client.GetAsync("https://localhost:44345/api/Pg/" + id))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        Item = JsonConvert.DeserializeObject<Pg>(apiResponse);
                    }
                    b.pg_Id = Item.pg_id;
                    b.UserId = Convert.ToInt32(HttpContext.Session.GetInt32("Userid"));
                    b.BookingDate = DateTime.Now;
                    b.No_ofMonth = 0;
                    b.TotalCost = 0;
                }
                return View(b);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Book(Book b)
        {
            _log4net.Info("Booking Done");
            if (HttpContext.Session.GetString("token") == null)
            {

                return RedirectToAction("Login", "Login");

            }
            else
            {

                Pg p = new Pg();

                using (var client = new HttpClient())
                {
                    var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                    client.DefaultRequestHeaders.Accept.Add(contentType);

                    client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));
                    
                    using (var response = await client.GetAsync("https://localhost:44345/api/Pg/" + b.pg_Id))
                    {

                        string apiResponse = await response.Content.ReadAsStringAsync();
                        p = JsonConvert.DeserializeObject<Pg>(apiResponse);
                    }
                 
                    b.TotalCost = b.No_ofMonth * p.Rent_per_month;
                    b.UserId= Convert.ToInt32(HttpContext.Session.GetInt32("Userid"));




                    StringContent content = new StringContent(JsonConvert.SerializeObject(b), Encoding.UTF8, "application/json");

                    using (var response = await client.PostAsync("https://localhost:44372/api/Booking/", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        b = JsonConvert.DeserializeObject<Book>(apiResponse);       
                    }
                }
                return RedirectToAction("Index");
            }
        }
        public async Task<IActionResult> GetBookingItems(int id)
        {
            _log4net.Info("Getting Booking details");
            if (HttpContext.Session.GetString("token") == null)
            {

                return RedirectToAction("Login", "Login");

            }
            else
            {
                List<Book> item = new List<Book>();
                ViewBag.Username = HttpContext.Session.GetString("Username");


                using (var client = new HttpClient())
                {


                    var contentType = new MediaTypeWithQualityHeaderValue("application/json");
                    client.DefaultRequestHeaders.Accept.Add(contentType);
                    if (HttpContext.Session.GetInt32("Userid") != null)
                    { id = Convert.ToInt32(HttpContext.Session.GetInt32("Userid")); }

                    client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("token"));

                    using (var response = await client.GetAsync("https://localhost:44372/api/Booking/" + id))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        item = JsonConvert.DeserializeObject<List<Book>>(apiResponse);
                    }
                }
                return View(item);
            }


        }
    }
    
    }

PgClientApplication/Views/PgList/Book.cshtml
@model PgClientApplication.Models.Book

@{
    ViewData["Title"] = "Book";
}

<h1>Book</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Book">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="pg_Id" class="control-label"></label>
                <input asp-for="pg_Id" class="form-control" readonly />
                <span asp-validation-for="pg_Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="BookingDate" class="control-label"></label>
                <input asp-for="BookingDate" class="form-control" />
                <span asp-validation-for="BookingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="No_ofMonth" class="control-label"></label>
                <input asp-for="No_ofMonth" class="form-control" />
                <span asp-validation-for="No_ofMonth" class="text-danger"></span>
            </div>
           

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PgClientApplication/Views/PgList/GetBookingItems.cshtml
@model IEnumerable<PgClientApplication.Models.Book>

@{
    ViewData["Title"] = "GetBookingItems";
}

<h1>Booking Details</h1>

<p>
    <h4>Booking Details</h4>
    <h5>Here is your Booking Details Mr./Mrs @ViewBag.Username.</h5>
    <h6>Thanks for choosing our service.</h6>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookingId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pg_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.No_ofMonth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalCost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookingId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pg_Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.No_ofMonth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalCost)
            </td>
           
        </tr>
}
    </tbody>
</table>

PgClientApplication/Views/PgList/Index.cshtml
@model IEnumerable<PgClientApplication.Models.Pg>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="btn-success" href="@Url.Action("GetBookingItems","PgList")">Booking Details</a>

</p>
<p>
    <a class="btn btn-danger align-content-end" href="@Url.Action("Logout","Login")">Logout</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.pg_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rent_per_month)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.pg_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rent_per_month)
                </td>
                <td>

                    <a class="btn btn-success" href="@Url.Action("Book","PgList",new { id = item.pg_id })">Book</a>

                </td>
            </tr>
        }
    </tbody>
</table>